language: python

env:
  - ANSIBLE_VERSION: "1.2.3"
  - ANSIBLE_VERSION: "1.3.4"
  - ANSIBLE_VERSION: "1.4.5"
  - ANSIBLE_VERSION: "1.5.5"
  - ANSIBLE_VERSION: "1.6.10"
  - ANSIBLE_VERSION: "1.7.2"
  - ANSIBLE_VERSION: "1.8.4"
  - ANSIBLE_VERSION: "1.9.6"
  - ANSIBLE_VERSION: "2.0.2"
  - ANSIBLE_VERSION: "2.1.6"
  - ANSIBLE_VERSION: "2.2.3"
  - ANSIBLE_VERSION: "2.3.3"
  - ANSIBLE_VERSION: "2.4.4"
  - ANSIBLE_VERSION: "2.5.3"

before_install:
  - sudo apt-get -y install software-properties-common
  - sudo apt-get -y install python-pip
  - sudo pip install ansible==$ANSIBLE_VERSION
  - ansible --version
  - cd tests
  - npm install
  - cd ..

script:
  - echo localhost > inventory
  - ansible-playbook -i inventory --connection=local --sudo --extra-vars "pwd=${PWD}" -v tests/main.yml

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
