---
- name: run task with global nodejs
  shell: "{{ grunt_executable }}grunt {{ item }}"
  args:
    chdir: "{{ chdir | default('.') }}"
  with_items: "{{ task | default('') }}"
  register: grunt_output1
  when: node_version is undefined

- name: run task in nvm
  shell: |
    nvm use {{ node_version }}
    {{ grunt_executable }}grunt {{ item }}
  args:
    chdir: "{{ chdir | default('.') }}"
  with_items: "{{ task | default('') }}"
  register: grunt_output2
  when: node_version is defined and nvm_init_script is undefined

- name: activate nvm and run task
  shell: |
    source {{ nvm_init_script }}
    nvm use {{ node_version }}
    {{ grunt_executable }}grunt {{ item }}
  args:
    chdir: "{{ chdir | default('.') }}"
    executable: /bin/bash
  with_items: "{{ task | default('') }}"
  register: grunt_output3
  when: node_version is defined and nvm_init_script is defined

- debug:
    msg: "{{ grunt_output1 }}"

- set_fact:
    grunt_output: "{{ grunt_output1 if grunt_output1 is not skipped else grunt_output2 if grunt_output2 is not skipped else grunt_output3 }}"
