---
- name: run task with global nodejs
  shell: "{{ grunt_executable }}grunt {{ item }}"
  args:
    chdir: "{{ chdir }}"
  with_items: "{{ task }}"
  register: grunt_output1
  when: node_version is undefined
  notify: set fact when run task with global nodejs

- name: run task in nvm
  shell: |
    nvm use {{ node_version }}
    {{ grunt_executable }}grunt {{ item }}
  args:
    chdir: "{{ chdir }}"
  with_items: "{{ task }}"
  register: grunt_output2
  when: node_version is defined and nvm_init_script is undefined
  notify: set fact when run task in nvm

- name: activate nvm and run task
  shell: |
    source {{ nvm_init_script }}
    nvm use {{ node_version }}
    {{ grunt_executable }}grunt {{ item }}
  args:
    chdir: "{{ chdir }}"
    executable: /bin/bash
  with_items: "{{ task }}"
  register: grunt_output3
  when: node_version is defined and nvm_init_script is defined
  notify: set fact when activate nvm and run task

- meta: flush_handlers
