---
- name: run task with global nodejs
  shell: "{{ grunt_executable }}grunt {{ item }}"
  args:
    chdir: "{{ chdir }}"
  with_items: "{{ task }}"
  register: grunt_output1
  when: node_version is undefined

- name: run task in nvm
  shell: |
    nvm use {{ node_version }}
    {{ grunt_executable }}grunt {{ item }}
  args:
    chdir: "{{ chdir }}"
  with_items: "{{ task }}"
  register: grunt_output2
  when: node_version is defined and nvm_init_script is undefined

- name: activate nvm and run task
  shell: |
    source {{ nvm_init_script }}
    nvm use {{ node_version }}
    {{ grunt_executable }}grunt {{ item }}
  args:
    chdir: "{{ chdir }}"
    executable: /bin/bash
  with_items: "{{ task }}"
  register: grunt_output3
  when: node_version is defined and nvm_init_script is defined

- set_fact:
    grunt_output: "{{ grunt_output1 }}"
  when: grunt_output1 is not skipped and grunt_output1.changed

- set_fact:
    grunt_output: "{{ grunt_output2 }}"
  when: grunt_output2 is not skipped and grunt_output2.changed

- set_fact:
    grunt_output: "{{ grunt_output3 }}"
  when: grunt_output3 is not skipped and grunt_output3.changed
