---
- name: run task with global nodejs
  shell: "{{ grunt_executable }}grunt {{ item }}"
  args:
    chdir: "{{ chdir | default('.') }}"
  with_items: "{{ task | default('') }}"
  register: grunt_output
  when: not node_version

- name: run task in nvm
  shell: |
    nvm use {{ node_version }}
    {{ grunt_executable }}grunt {{ item }}
  args:
    chdir: "{{ chdir | default('.') }}"
  with_items: "{{ task | default('') }}"
  register: grunt_output
  when: node_version and not nvm_init_script

- name: activate nvm and run task
  shell: |
    source {{ nvm_init_script }}
    nvm use {{ node_version }}
    {{ grunt_executable }}grunt {{ item }}
  args:
    chdir: "{{ chdir | default('.') }}"
    executable: /bin/bash
  with_items: "{{ task | default('') }}"
  register: grunt_output
  when: node_version and nvm_init_script
